### ISSUE TITLE
Wrong admin link

### ISSUE THREAD

**Issue by tim-krieger** [kitsteam/mindwendel#14]
Steps to reproduce (https//idea.kits.blog)

1. Create a brainstorming
2. Got to settings
3. Copy this link and follow it with another browser

Gives me a 404 failure...

After deleting the port in this link everything works like exspected.

![image](https://user-images.githubusercontent.com/64839715/110237541-ea43a880-7f3c-11eb-8514-5c38bcc9819b.png)

**Comment by tim-krieger** [comment]
Duplicate :)

https://github.com/mindwendel/mindwendel/issues/78

**Comment by JannikStreek** [comment]
i think you can fix it, if you add `PORT: 80` to your docker compose environment. The link is actually correct, but the docker forwards port 4000 to 80. So if you start the internal app on port 80 and map 80:80 it should work.

**Comment by tim-krieger** [comment]
I think this issue is related to plesk. We run different services and bind them with docker proxy rules to a specific domain. The mindwendel container doesn't start when I add this line and/or change the ports section.

Strangly the share link (not the admin link) is generated successfully.

**Comment by JannikStreek** [comment]
well, i dont think its an issue with plesk. The configured port (4000) is used only internaly within the docker container. So it should not matter what kind of port you are using there. The important part (maybe in your config) is to what target port you are mapping to. If its the same you have used before, it shouldnt be a problem.

Good point with the share link - it uses a different method to get the link (uri in live views). Apparently its implemented differently - but its not available there. I can think of workarounds, but we are using the right function to generate the url. Its just a configuration/docker issue.

I would even consider changing our default compose file to use port 80 in the docker container, I currently don't see any reason for port 4000 anymore. Its just the default port for the dev server.

```
services:
  mindwendel:
    container_name: mindwendel
    build:
      context: .
      target: app
    environment:
      # adjust these vars in production!
      DATABASE_USER: postgres
      DATABASE_USER_PASSWORD: postgres
      DATABASE_NAME: mindwendel
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      DATABASE_SSL: "false"
      PORT: 80
      MW_DEFAULT_LOCALE: en
      # run mix phx.gen.secret
      SECRET_KEY_BASE: ...
      URL_HOST: localhost
    ports:
      - "80:80"
```
